/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DecisionCenterRouteImport } from './routes/decision-center'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as InventoryAnomaliesRouteImport } from './routes/inventory-anomalies'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as PickingRouteImport } from './routes/picking'
import { Route as QualityCheckRouteImport } from './routes/quality-check'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WarehouseOperationsRouteImport } from './routes/warehouse-operations'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as CustomerDashboardRouteImport } from './routes/customer/dashboard'
import { Route as CustomerNotificationsRouteImport } from './routes/customer/notifications'
import { Route as CustomerOrdersRouteImport } from './routes/customer/orders'
import { Route as CustomerProfileRouteImport } from './routes/customer/profile'
import { Route as ExceptionsIndexRouteImport } from './routes/exceptions/index'
import { Route as ExceptionsExceptionIdRouteImport } from './routes/exceptions/$exceptionId'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as InventorySkuRouteImport } from './routes/inventory/$sku'
import { Route as LoginAdminRouteImport } from './routes/login/admin'
import { Route as LoginCustomerRouteImport } from './routes/login/customer'
import { Route as LoginManagerRouteImport } from './routes/login/manager'
import { Route as LoginWorkerRouteImport } from './routes/login/worker'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as OrdersNewRouteImport } from './routes/orders/new'
import { Route as WorkerDashboardRouteImport } from './routes/worker/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionCenterRoute = DecisionCenterRouteImport.update({
  id: '/decision-center',
  path: '/decision-center',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryAnomaliesRoute = InventoryAnomaliesRouteImport.update({
  id: '/inventory-anomalies',
  path: '/inventory-anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const PickingRoute = PickingRouteImport.update({
  id: '/picking',
  path: '/picking',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityCheckRoute = QualityCheckRouteImport.update({
  id: '/quality-check',
  path: '/quality-check',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseOperationsRoute = WarehouseOperationsRouteImport.update({
  id: '/warehouse-operations',
  path: '/warehouse-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/customer/notifications',
  path: '/customer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/customer/orders',
  path: '/customer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/customer/profile',
  path: '/customer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsIndexRoute = ExceptionsIndexRouteImport.update({
  id: '/exceptions/',
  path: '/exceptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsExceptionIdRoute = ExceptionsExceptionIdRouteImport.update({
  id: '/exceptions/$exceptionId',
  path: '/exceptions/$exceptionId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySkuRoute = InventorySkuRouteImport.update({
  id: '/inventory/$sku',
  path: '/inventory/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCustomerRoute = LoginCustomerRouteImport.update({
  id: '/login/customer',
  path: '/login/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginManagerRoute = LoginManagerRouteImport.update({
  id: '/login/manager',
  path: '/login/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginWorkerRoute = LoginWorkerRouteImport.update({
  id: '/login/worker',
  path: '/login/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersNewRoute = OrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerDashboardRoute = WorkerDashboardRouteImport.update({
  id: '/worker/dashboard',
  path: '/worker/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/allocation': typeof AllocationRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/decision-center': typeof DecisionCenterRoute
  '/dispatch': typeof DispatchRoute
  '/feedback': typeof FeedbackRoute
  '/finance': typeof FinanceRoute
  '/inventory-anomalies': typeof InventoryAnomaliesRoute
  '/packing': typeof PackingRoute
  '/picking': typeof PickingRoute
  '/quality-check': typeof QualityCheckRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracking': typeof TrackingRoute
  '/users': typeof UsersRoute
  '/warehouse-operations': typeof WarehouseOperationsRoute
  '/workforce': typeof WorkforceRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
  '/inventory/$sku': typeof InventorySkuRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/customer': typeof LoginCustomerRoute
  '/login/manager': typeof LoginManagerRoute
  '/login/worker': typeof LoginWorkerRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/exceptions/': typeof ExceptionsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/allocation': typeof AllocationRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/decision-center': typeof DecisionCenterRoute
  '/dispatch': typeof DispatchRoute
  '/feedback': typeof FeedbackRoute
  '/finance': typeof FinanceRoute
  '/inventory-anomalies': typeof InventoryAnomaliesRoute
  '/packing': typeof PackingRoute
  '/picking': typeof PickingRoute
  '/quality-check': typeof QualityCheckRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracking': typeof TrackingRoute
  '/users': typeof UsersRoute
  '/warehouse-operations': typeof WarehouseOperationsRoute
  '/workforce': typeof WorkforceRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
  '/inventory/$sku': typeof InventorySkuRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/customer': typeof LoginCustomerRoute
  '/login/manager': typeof LoginManagerRoute
  '/login/worker': typeof LoginWorkerRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/exceptions': typeof ExceptionsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/allocation': typeof AllocationRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/decision-center': typeof DecisionCenterRoute
  '/dispatch': typeof DispatchRoute
  '/feedback': typeof FeedbackRoute
  '/finance': typeof FinanceRoute
  '/inventory-anomalies': typeof InventoryAnomaliesRoute
  '/packing': typeof PackingRoute
  '/picking': typeof PickingRoute
  '/quality-check': typeof QualityCheckRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tracking': typeof TrackingRoute
  '/users': typeof UsersRoute
  '/warehouse-operations': typeof WarehouseOperationsRoute
  '/workforce': typeof WorkforceRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/exceptions/$exceptionId': typeof ExceptionsExceptionIdRoute
  '/inventory/$sku': typeof InventorySkuRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/customer': typeof LoginCustomerRoute
  '/login/manager': typeof LoginManagerRoute
  '/login/worker': typeof LoginWorkerRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/new': typeof OrdersNewRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/exceptions/': typeof ExceptionsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/allocation'
    | '/analytics'
    | '/dashboard'
    | '/decision-center'
    | '/dispatch'
    | '/feedback'
    | '/finance'
    | '/inventory-anomalies'
    | '/packing'
    | '/picking'
    | '/quality-check'
    | '/settings'
    | '/simulator'
    | '/sitemap.xml'
    | '/tracking'
    | '/users'
    | '/warehouse-operations'
    | '/workforce'
    | '/customer/dashboard'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/exceptions/$exceptionId'
    | '/inventory/$sku'
    | '/login/admin'
    | '/login/customer'
    | '/login/manager'
    | '/login/worker'
    | '/orders/$orderId'
    | '/orders/new'
    | '/worker/dashboard'
    | '/exceptions/'
    | '/inventory/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/allocation'
    | '/analytics'
    | '/dashboard'
    | '/decision-center'
    | '/dispatch'
    | '/feedback'
    | '/finance'
    | '/inventory-anomalies'
    | '/packing'
    | '/picking'
    | '/quality-check'
    | '/settings'
    | '/simulator'
    | '/sitemap.xml'
    | '/tracking'
    | '/users'
    | '/warehouse-operations'
    | '/workforce'
    | '/customer/dashboard'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/exceptions/$exceptionId'
    | '/inventory/$sku'
    | '/login/admin'
    | '/login/customer'
    | '/login/manager'
    | '/login/worker'
    | '/orders/$orderId'
    | '/orders/new'
    | '/worker/dashboard'
    | '/exceptions'
    | '/inventory'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/allocation'
    | '/analytics'
    | '/dashboard'
    | '/decision-center'
    | '/dispatch'
    | '/feedback'
    | '/finance'
    | '/inventory-anomalies'
    | '/packing'
    | '/picking'
    | '/quality-check'
    | '/settings'
    | '/simulator'
    | '/sitemap.xml'
    | '/tracking'
    | '/users'
    | '/warehouse-operations'
    | '/workforce'
    | '/customer/dashboard'
    | '/customer/notifications'
    | '/customer/orders'
    | '/customer/profile'
    | '/exceptions/$exceptionId'
    | '/inventory/$sku'
    | '/login/admin'
    | '/login/customer'
    | '/login/manager'
    | '/login/worker'
    | '/orders/$orderId'
    | '/orders/new'
    | '/worker/dashboard'
    | '/exceptions/'
    | '/inventory/'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AllocationRoute: typeof AllocationRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  DecisionCenterRoute: typeof DecisionCenterRoute
  DispatchRoute: typeof DispatchRoute
  FeedbackRoute: typeof FeedbackRoute
  FinanceRoute: typeof FinanceRoute
  InventoryAnomaliesRoute: typeof InventoryAnomaliesRoute
  PackingRoute: typeof PackingRoute
  PickingRoute: typeof PickingRoute
  QualityCheckRoute: typeof QualityCheckRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackingRoute: typeof TrackingRoute
  UsersRoute: typeof UsersRoute
  WarehouseOperationsRoute: typeof WarehouseOperationsRoute
  WorkforceRoute: typeof WorkforceRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  ExceptionsExceptionIdRoute: typeof ExceptionsExceptionIdRoute
  InventorySkuRoute: typeof InventorySkuRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginCustomerRoute: typeof LoginCustomerRoute
  LoginManagerRoute: typeof LoginManagerRoute
  LoginWorkerRoute: typeof LoginWorkerRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersNewRoute: typeof OrdersNewRoute
  WorkerDashboardRoute: typeof WorkerDashboardRoute
  ExceptionsIndexRoute: typeof ExceptionsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-center': {
      id: '/decision-center'
      path: '/decision-center'
      fullPath: '/decision-center'
      preLoaderRoute: typeof DecisionCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-anomalies': {
      id: '/inventory-anomalies'
      path: '/inventory-anomalies'
      fullPath: '/inventory-anomalies'
      preLoaderRoute: typeof InventoryAnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picking': {
      id: '/picking'
      path: '/picking'
      fullPath: '/picking'
      preLoaderRoute: typeof PickingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-check': {
      id: '/quality-check'
      path: '/quality-check'
      fullPath: '/quality-check'
      preLoaderRoute: typeof QualityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-operations': {
      id: '/warehouse-operations'
      path: '/warehouse-operations'
      fullPath: '/warehouse-operations'
      preLoaderRoute: typeof WarehouseOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/customer/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/customer/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/customer/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions/': {
      id: '/exceptions/'
      path: '/exceptions'
      fullPath: '/exceptions/'
      preLoaderRoute: typeof ExceptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions/$exceptionId': {
      id: '/exceptions/$exceptionId'
      path: '/exceptions/$exceptionId'
      fullPath: '/exceptions/$exceptionId'
      preLoaderRoute: typeof ExceptionsExceptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$sku': {
      id: '/inventory/$sku'
      path: '/inventory/$sku'
      fullPath: '/inventory/$sku'
      preLoaderRoute: typeof InventorySkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/customer': {
      id: '/login/customer'
      path: '/login/customer'
      fullPath: '/login/customer'
      preLoaderRoute: typeof LoginCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/manager': {
      id: '/login/manager'
      path: '/login/manager'
      fullPath: '/login/manager'
      preLoaderRoute: typeof LoginManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/worker': {
      id: '/login/worker'
      path: '/login/worker'
      fullPath: '/login/worker'
      preLoaderRoute: typeof LoginWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/new': {
      id: '/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof OrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/dashboard': {
      id: '/worker/dashboard'
      path: '/worker/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof WorkerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AllocationRoute: AllocationRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  DecisionCenterRoute: DecisionCenterRoute,
  DispatchRoute: DispatchRoute,
  FeedbackRoute: FeedbackRoute,
  FinanceRoute: FinanceRoute,
  InventoryAnomaliesRoute: InventoryAnomaliesRoute,
  PackingRoute: PackingRoute,
  PickingRoute: PickingRoute,
  QualityCheckRoute: QualityCheckRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackingRoute: TrackingRoute,
  UsersRoute: UsersRoute,
  WarehouseOperationsRoute: WarehouseOperationsRoute,
  WorkforceRoute: WorkforceRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  ExceptionsExceptionIdRoute: ExceptionsExceptionIdRoute,
  InventorySkuRoute: InventorySkuRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginCustomerRoute: LoginCustomerRoute,
  LoginManagerRoute: LoginManagerRoute,
  LoginWorkerRoute: LoginWorkerRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersNewRoute: OrdersNewRoute,
  WorkerDashboardRoute: WorkerDashboardRoute,
  ExceptionsIndexRoute: ExceptionsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
